import { attachThumbnail, buildBlocksFromNodes } from "./utils";
import { TemplateDefinition } from "./types";

const width = 240;
const height = 140;
const spacing = 240;

const definition: TemplateDefinition = {
  name: "AI Prompt Blueprint",
  nodes: [
    {
      id: "prompt-context",
      title: "Context",
      subtitle: "Background",
      type: "flow-input",
      x: 0,
      y: 0,
      width,
      height,
      placeholder: "Provide the product/story background...",
      style: "canvasBlock",
    },
    {
      id: "prompt-role",
      title: "Role & Tone",
      subtitle: "Who is speaking",
      type: "flow-agent",
      x: spacing,
      y: 0,
      width,
      height,
      placeholder: "e.g. Senior UX Writer, precise, encouraging...",
      style: "canvasBlock",
    },
    {
      id: "prompt-task",
      title: "Task",
      subtitle: "What to produce",
      type: "flow-text-gen",
      x: spacing * 2,
      y: 0,
      width,
      height,
      placeholder: "Describe the exact deliverable...",
      style: "canvasBlock",
    },
    {
      id: "prompt-constraints",
      title: "Constraints",
      subtitle: "Rules & limits",
      type: "flow-state",
      x: 0,
      y: spacing * 0.8,
      width,
      height,
      placeholder: "Length, format, brand guardrails...",
      style: "canvasBlock",
    },
    {
      id: "prompt-examples",
      title: "Examples",
      subtitle: "Few-shot cues",
      type: "flow-text-gen",
      x: spacing,
      y: spacing * 0.8,
      width,
      height,
      placeholder: "Provide 2-3 samples or outlines...",
      style: "canvasBlock",
    },
    {
      id: "prompt-output",
      title: "Output Format",
      subtitle: "Structure",
      type: "flow-tool",
      x: spacing * 2,
      y: spacing * 0.8,
      width,
      height,
      placeholder: "Markdown sections, bullet rules, JSON schema...",
      style: "canvasBlock",
    },
    {
      id: "prompt-review",
      title: "Review",
      subtitle: "Acceptance criteria",
      type: "flow-text-gen",
      x: spacing,
      y: spacing * 1.6,
      width,
      height,
      placeholder: "Checklist to confirm the prompt is done...",
      style: "canvasBlock",
    },
  ],
  connections: [
    { source: "prompt-context", target: "prompt-role" },
    { source: "prompt-role", target: "prompt-task" },
    { source: "prompt-task", target: "prompt-output" },
    { source: "prompt-constraints", target: "prompt-task" },
    { source: "prompt-examples", target: "prompt-output" },
    { source: "prompt-output", target: "prompt-review" },
  ],
  thumbnail: "",
};

export const AIPromptBlueprint = attachThumbnail(definition, buildBlocksFromNodes(definition.nodes));
