import { attachThumbnail, buildBlocksFromNodes } from "./utils";
import { TemplateDefinition } from "./types";

const baseWidth = 230;
const baseHeight = 130;
const columnSpacing = 250;
const rowSpacing = 160;

const definition: TemplateDefinition = {
  name: "Business Model Canvas",
  nodes: [
    {
      id: "bmc-key-partners",
      title: "Key Partners",
      subtitle: "Alliances & suppliers",
      type: "flow-input",
      x: 0,
      y: 0,
      width: baseWidth,
      height: baseHeight,
      placeholder: "List your key partners and suppliers...",
      style: "canvasBlock",
    },
    {
      id: "bmc-value-prop",
      title: "Value Proposition",
      subtitle: "What makes you special",
      type: "flow-text-gen",
      x: columnSpacing,
      y: 0,
      width: baseWidth,
      height: baseHeight,
      placeholder: "Describe the core value you provide...",
      style: "canvasBlock",
    },
    {
      id: "bmc-customer-segments",
      title: "Customer Segments",
      subtitle: "Who you serve",
      type: "flow-agent",
      x: columnSpacing * 2,
      y: 0,
      width: baseWidth,
      height: baseHeight,
      placeholder: "Define your primary and secondary segments...",
      style: "canvasBlock",
    },
    {
      id: "bmc-key-activities",
      title: "Key Activities",
      subtitle: "Critical actions",
      type: "flow-text-gen",
      x: 0,
      y: rowSpacing,
      width: baseWidth,
      height: baseHeight,
      placeholder: "List the main activities to deliver value...",
      style: "canvasBlock",
    },
    {
      id: "bmc-channels",
      title: "Channels",
      subtitle: "How you reach users",
      type: "flow-text-gen",
      x: columnSpacing,
      y: rowSpacing,
      width: baseWidth,
      height: baseHeight,
      placeholder: "Outline acquisition & delivery channels...",
      style: "canvasBlock",
    },
    {
      id: "bmc-customer-relationships",
      title: "Customer Relationships",
      subtitle: "Expectations & support",
      type: "flow-text-gen",
      x: columnSpacing * 2,
      y: rowSpacing,
      width: baseWidth,
      height: baseHeight,
      placeholder: "Describe onboarding, service, retention...",
      style: "canvasBlock",
    },
    {
      id: "bmc-key-resources",
      title: "Key Resources",
      subtitle: "What you need",
      type: "flow-state",
      x: 0,
      y: rowSpacing * 2,
      width: baseWidth,
      height: baseHeight,
      placeholder: "Team, tech, capital, IP...",
      style: "canvasBlock",
    },
    {
      id: "bmc-cost-structure",
      title: "Cost Structure",
      subtitle: "Where money goes",
      type: "flow-tool",
      x: columnSpacing,
      y: rowSpacing * 2,
      width: baseWidth,
      height: baseHeight,
      placeholder: "Fixed vs variable costs, major expenses...",
      style: "canvasBlock",
    },
    {
      id: "bmc-revenue-streams",
      title: "Revenue Streams",
      subtitle: "How money comes in",
      type: "flow-text-gen",
      x: columnSpacing * 2,
      y: rowSpacing * 2,
      width: baseWidth,
      height: baseHeight,
      placeholder: "Subscription, transaction, ads...",
      style: "canvasBlock",
    },
  ],
  connections: [
    { source: "bmc-key-partners", target: "bmc-value-prop" },
    { source: "bmc-key-activities", target: "bmc-value-prop" },
    { source: "bmc-value-prop", target: "bmc-customer-segments" },
    { source: "bmc-channels", target: "bmc-customer-relationships" },
    { source: "bmc-customer-relationships", target: "bmc-revenue-streams" },
    { source: "bmc-cost-structure", target: "bmc-revenue-streams" },
  ],
  thumbnail: "",
};

export const BusinessModelCanvas = attachThumbnail(definition, buildBlocksFromNodes(definition.nodes));
