import { attachThumbnail, buildBlocksFromNodes } from "./utils";
import { TemplateDefinition } from "./types";

const width = 230;
const height = 130;
const col = 250;
const row = 160;

const definition: TemplateDefinition = {
  name: "Lean Canvas",
  nodes: [
    {
      id: "lean-problem",
      title: "Problem",
      subtitle: "Top pains",
      type: "flow-input",
      x: 0,
      y: 0,
      width,
      height,
      placeholder: "List the top 3 problems your users face...",
      style: "canvasBlock",
    },
    {
      id: "lean-solution",
      title: "Solution",
      subtitle: "How you solve it",
      type: "flow-text-gen",
      x: col,
      y: 0,
      width,
      height,
      placeholder: "Describe the minimum solution that addresses the problems...",
      style: "canvasBlock",
    },
    {
      id: "lean-unique-value",
      title: "Unique Value Proposition",
      subtitle: "Why you stand out",
      type: "flow-text-gen",
      x: col * 2,
      y: 0,
      width,
      height,
      placeholder: "Craft a clear, compelling UVP...",
      style: "canvasBlock",
    },
    {
      id: "lean-unfair-advantage",
      title: "Unfair Advantage",
      subtitle: "Hard to copy",
      type: "flow-agent",
      x: 0,
      y: row,
      width,
      height,
      placeholder: "Proprietary data, relationships, insight...",
      style: "canvasBlock",
    },
    {
      id: "lean-key-metrics",
      title: "Key Metrics",
      subtitle: "Track progress",
      type: "flow-state",
      x: col,
      y: row,
      width,
      height,
      placeholder: "Activation, retention, MRR, NPS...",
      style: "canvasBlock",
    },
    {
      id: "lean-channels",
      title: "Channels",
      subtitle: "Acquisition paths",
      type: "flow-text-gen",
      x: col * 2,
      y: row,
      width,
      height,
      placeholder: "Organic, paid, partnerships...",
      style: "canvasBlock",
    },
    {
      id: "lean-customer-segments",
      title: "Customer Segments",
      subtitle: "Who feels the pain",
      type: "flow-text-gen",
      x: 0,
      y: row * 2,
      width,
      height,
      placeholder: "Archetypes, early adopters, niches...",
      style: "canvasBlock",
    },
    {
      id: "lean-cost-structure",
      title: "Cost Structure",
      subtitle: "Spend profile",
      type: "flow-tool",
      x: col,
      y: row * 2,
      width,
      height,
      placeholder: "Key costs to deliver the solution...",
      style: "canvasBlock",
    },
    {
      id: "lean-revenue-streams",
      title: "Revenue Streams",
      subtitle: "How you earn",
      type: "flow-text-gen",
      x: col * 2,
      y: row * 2,
      width,
      height,
      placeholder: "Pricing model, monetization paths...",
      style: "canvasBlock",
    },
  ],
  connections: [
    { source: "lean-problem", target: "lean-solution" },
    { source: "lean-solution", target: "lean-unique-value" },
    { source: "lean-unique-value", target: "lean-channels" },
    { source: "lean-problem", target: "lean-customer-segments" },
    { source: "lean-customer-segments", target: "lean-revenue-streams" },
    { source: "lean-cost-structure", target: "lean-revenue-streams" },
  ],
  thumbnail: "",
};

export const LeanCanvas = attachThumbnail(definition, buildBlocksFromNodes(definition.nodes));
