import React, { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Copy, Check, Code, FileJson, Download, Upload } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import type { HeroBackgroundSettings } from "./HeroBackgroundWorkspace";
import { buildHeroGradient } from "./heroGradient";

interface HeroExportPanelProps {
  isOpen: boolean;
  onClose: () => void;
  settings: HeroBackgroundSettings;
  onImportSettings: (settings: HeroBackgroundSettings) => void;
}

// Generate CSS gradient based on settings
const generateGradientCSS = (settings: HeroBackgroundSettings): string => {
  return buildHeroGradient(settings);
};

// Generate button gradient style
const generateButtonGradient = (
  gradientType: "none" | "linear" | "radial" | "glossy" | "glow",
  baseColor: string,
  gradientColor: string
): string => {
  switch (gradientType) {
    case "linear":
      return `linear-gradient(135deg, ${baseColor}, ${gradientColor})`;
    case "radial":
      return `radial-gradient(circle at 30% 30%, ${gradientColor}, ${baseColor})`;
    case "glossy":
      return `linear-gradient(180deg, ${gradientColor}40 0%, transparent 50%, ${baseColor}20 100%), ${baseColor}`;
    case "glow":
      return baseColor;
    default:
      return baseColor;
  }
};

// Generate card gradient style
const generateCardGradient = (
  gradientType: "none" | "linear" | "radial" | "glossy" | "glass",
  baseColor: string,
  gradientColor: string
): string => {
  switch (gradientType) {
    case "linear":
      return `linear-gradient(135deg, ${baseColor}, ${gradientColor}30)`;
    case "radial":
      return `radial-gradient(circle at 0% 0%, ${gradientColor}40, ${baseColor})`;
    case "glossy":
      return `linear-gradient(180deg, rgba(255,255,255,0.15) 0%, transparent 50%, rgba(0,0,0,0.1) 100%), ${baseColor}`;
    case "glass":
      return baseColor;
    default:
      return baseColor;
  }
};

// Generate React component code for Background
const generateBackgroundComponent = (settings: HeroBackgroundSettings): string => {
  const gradientCSS = generateGradientCSS(settings);
  const grainSVG = `data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='5' stitchTiles='stitch'/%3E%3CfeColorMatrix type='saturate' values='0'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E`;

  // Build filter — must match the live preview exactly
  const b = settings.brightness * (settings.exposure ?? 1);
  const c = (settings.contrast ?? 1) * (settings.gamma ?? 1);
  const s = settings.saturation ?? 1;
  const filterParts = [`brightness(${b.toFixed(2)})`, `contrast(${c.toFixed(2)})`, `saturate(${s})`];
  if (settings.blurPx && settings.blurPx > 0) filterParts.push(`blur(${settings.blurPx}px)`);
  const filterString = filterParts.join(" ");

  const vignetteOverlay = (settings.vignette && settings.vignette > 0)
    ? `
      {/* Vignette overlay */}
      <div 
        className="absolute inset-0 pointer-events-none"
        style={{
          background: "radial-gradient(ellipse 75% 65% at 50% 50%, transparent 35%, rgba(0,0,0,0.15) 65%, rgba(0,0,0,0.5) 100%)",
          opacity: ${settings.vignette},
          mixBlendMode: "multiply",
        }}
      />`
    : "";

  const grainOverlay = settings.grainEnabled
    ? `
      {/* Grain overlay */}
      <div 
        className="absolute inset-0 pointer-events-none"
        style={{
          backgroundImage: \`url("${grainSVG}")\`,
          opacity: ${(settings.grainIntensity * 0.25).toFixed(3)},
          mixBlendMode: "overlay" as const,
        }}
      />`
    : "";

  return `import React from "react";

/**
 * HeroBackground Component
 * Generated by Beymflow Hero Background Generator
 * 
 * Style: ${settings.gradientStyle}
 * Colors: ${settings.singleColorMode ? settings.color1 : `${settings.color1}, ${settings.color2}, ${settings.color3}, ${settings.color4}`}
 */

interface HeroBackgroundProps {
  children?: React.ReactNode;
  className?: string;
}

export const HeroBackground: React.FC<HeroBackgroundProps> = ({ children, className }) => {
  return (
    <div 
      className={\`relative w-full h-screen overflow-hidden \${className || ""}\`}
      style={{
        background: "${gradientCSS}",
        filter: "${filterString}",${settings.blendMode && settings.blendMode !== "normal" ? `\n        mixBlendMode: "${settings.blendMode}",` : ""}
      }}
    >${grainOverlay}${vignetteOverlay}
      
      {/* Content */}
      {children && (
        <div className="relative z-10 h-full">
          {children}
        </div>
      )}
    </div>
  );
};

export default HeroBackground;

// Usage:
// <HeroBackground>
//   <YourHeroContent />
// </HeroBackground>
`;
};

// Generate React component code for Components
const generateComponentsCode = (settings: HeroBackgroundSettings): string => {
  const primaryBtnBg = generateButtonGradient(
    settings.buttonPrimaryGradient,
    settings.buttonPrimaryBg,
    settings.buttonPrimaryGradientColor
  );

  const secondaryBtnBg = generateButtonGradient(
    settings.buttonSecondaryGradient,
    settings.buttonSecondaryBg,
    settings.buttonSecondaryGradientColor
  );

  const cardBackground = generateCardGradient(
    settings.cardGradient,
    settings.cardBg,
    settings.cardGradientColor
  );

  const primaryGlowStyle = settings.buttonPrimaryGradient === "glow"
    ? `boxShadow: "0 0 20px ${settings.buttonPrimaryGradientColor}60, 0 0 40px ${settings.buttonPrimaryGradientColor}30",`
    : "";

  const secondaryGlowStyle = settings.buttonSecondaryGradient === "glow"
    ? `boxShadow: "0 0 20px ${settings.buttonSecondaryGradientColor}60, 0 0 40px ${settings.buttonSecondaryGradientColor}30",`
    : "";

  const cardGlassStyle = settings.cardGradient === "glass"
    ? `backdropFilter: "blur(12px)",
      WebkitBackdropFilter: "blur(12px)",`
    : "";

  return `import React from "react";

/**
 * UI Components
 * Generated by Beymflow Hero Background Generator
 * 
 * Includes: PrimaryButton, SecondaryButton, Card, Input
 */

// ============ Primary Button ============
interface PrimaryButtonProps {
  children: React.ReactNode;
  onClick?: () => void;
  className?: string;
}

export const PrimaryButton: React.FC<PrimaryButtonProps> = ({ children, onClick, className }) => {
  return (
    <button
      onClick={onClick}
      className={\`px-6 py-3 rounded-lg font-medium transition-all hover:opacity-90 hover:scale-[1.02] active:scale-[0.98] \${className || ""}\`}
      style={{
        background: "${primaryBtnBg}",
        color: "${settings.buttonPrimaryText}",
        ${primaryGlowStyle}
      }}
    >
      {children}
    </button>
  );
};

// ============ Secondary Button ============
interface SecondaryButtonProps {
  children: React.ReactNode;
  onClick?: () => void;
  className?: string;
}

export const SecondaryButton: React.FC<SecondaryButtonProps> = ({ children, onClick, className }) => {
  return (
    <button
      onClick={onClick}
      className={\`px-6 py-3 rounded-lg font-medium transition-all hover:opacity-90 hover:scale-[1.02] active:scale-[0.98] \${className || ""}\`}
      style={{
        background: "${secondaryBtnBg}",
        color: "${settings.buttonSecondaryText}",
        border: "1px solid ${settings.buttonSecondaryBorder}",
        ${secondaryGlowStyle}
      }}
    >
      {children}
    </button>
  );
};

// ============ Card ============
interface CardProps {
  children: React.ReactNode;
  className?: string;
}

export const Card: React.FC<CardProps> = ({ children, className }) => {
  return (
    <div
      className={\`rounded-xl p-6 \${className || ""}\`}
      style={{
        background: "${cardBackground}",
        border: "1px solid ${settings.cardBorder}",
        ${cardGlassStyle}
      }}
    >
      {children}
    </div>
  );
};

// ============ Input ============
interface InputProps {
  placeholder?: string;
  value?: string;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  className?: string;
}

export const Input: React.FC<InputProps> = ({ placeholder, value, onChange, className }) => {
  return (
    <input
      type="text"
      placeholder={placeholder}
      value={value}
      onChange={onChange}
      className={\`w-full px-4 py-3 rounded-lg transition-all outline-none \${className || ""}\`}
      style={{
        background: "${settings.inputBg}",
        border: "1px solid ${settings.inputBorder}",
        color: "${settings.inputText}",
      }}
      onFocus={(e) => {
        e.target.style.borderColor = "${settings.focusRingColor}";
        e.target.style.boxShadow = "0 0 0 2px ${settings.focusRingColor}40";
      }}
      onBlur={(e) => {
        e.target.style.borderColor = "${settings.inputBorder}";
        e.target.style.boxShadow = "none";
      }}
    />
  );
};

// Usage:
// <PrimaryButton onClick={() => console.log("clicked")}>Get Started</PrimaryButton>
// <SecondaryButton>Learn More</SecondaryButton>
// <Card><p>Card content here</p></Card>
// <Input placeholder="Enter your email" />
`;
};

// Generate settings JSON
const generateSettingsJSON = (settings: HeroBackgroundSettings): string => {
  return JSON.stringify({
    version: "1.0",
    generator: "beymflow-hero-background",
    settings: {
      colors: {
        color1: settings.color1,
        color2: settings.color2,
        color3: settings.color3,
        color4: settings.color4,
        singleColorMode: settings.singleColorMode,
      },
      effects: {
        brightness: settings.brightness,
        contrast: settings.contrast,
        saturation: settings.saturation,
        blurPx: settings.blurPx,
        vignette: settings.vignette,
        grainEnabled: settings.grainEnabled,
        grainIntensity: settings.grainIntensity,
        environmentEnabled: settings.environmentEnabled,
      },
      style: {
        gradientStyle: settings.gradientStyle,
        motionEnabled: settings.motionEnabled,
        motionSpeed: settings.motionSpeed,
      },
      components: {
        buttonPrimaryBg: settings.buttonPrimaryBg,
        buttonPrimaryText: settings.buttonPrimaryText,
        buttonPrimaryGradient: settings.buttonPrimaryGradient,
        buttonPrimaryGradientColor: settings.buttonPrimaryGradientColor,
        buttonPrimaryRadius: settings.buttonPrimaryRadius,
        buttonPrimaryPaddingX: settings.buttonPrimaryPaddingX,
        buttonPrimaryPaddingY: settings.buttonPrimaryPaddingY,
        buttonSecondaryBg: settings.buttonSecondaryBg,
        buttonSecondaryText: settings.buttonSecondaryText,
        buttonSecondaryBorder: settings.buttonSecondaryBorder,
        buttonSecondaryGradient: settings.buttonSecondaryGradient,
        buttonSecondaryGradientColor: settings.buttonSecondaryGradientColor,
        buttonSecondaryRadius: settings.buttonSecondaryRadius,
        buttonSecondaryPaddingX: settings.buttonSecondaryPaddingX,
        buttonSecondaryPaddingY: settings.buttonSecondaryPaddingY,
        cardBg: settings.cardBg,
        cardBorder: settings.cardBorder,
        cardGradient: settings.cardGradient,
        cardGradientColor: settings.cardGradientColor,
        inputBg: settings.inputBg,
        inputBorder: settings.inputBorder,
        inputText: settings.inputText,
        focusRingColor: settings.focusRingColor,
      },
    },
  }, null, 2);
};

// Parse imported JSON to settings
const parseSettingsJSON = (json: string): HeroBackgroundSettings | null => {
  try {
    const parsed = JSON.parse(json);
    if (parsed.settings) {
      return {
        color1: parsed.settings.colors?.color1 || "#000000",
        color2: parsed.settings.colors?.color2 || "#1a1a1a",
        color3: parsed.settings.colors?.color3 || "#389cff",
        color4: parsed.settings.colors?.color4 || "#8b5cf6",
        singleColorMode: parsed.settings.colors?.singleColorMode || false,
        brightness: parsed.settings.effects?.brightness || 1.2,
        contrast: parsed.settings.effects?.contrast ?? 1,
        saturation: parsed.settings.effects?.saturation ?? 1,
        blurPx: parsed.settings.effects?.blurPx ?? 0,
        vignette: parsed.settings.effects?.vignette ?? 0,
        grainEnabled: parsed.settings.effects?.grainEnabled ?? true,
        grainIntensity: parsed.settings.effects?.grainIntensity || 0.35,
        environmentEnabled: parsed.settings.effects?.environmentEnabled ?? true,
        gradientStyle: parsed.settings.style?.gradientStyle || "halo",
        motionEnabled: parsed.settings.style?.motionEnabled || false,
        motionSpeed: parsed.settings.style?.motionSpeed || 0.5,
        buttonPrimaryBg: parsed.settings.components?.buttonPrimaryBg || "#ffffff",
        buttonPrimaryText: parsed.settings.components?.buttonPrimaryText || "#000000",
        buttonPrimaryGradient: parsed.settings.components?.buttonPrimaryGradient || "none",
        buttonPrimaryGradientColor: parsed.settings.components?.buttonPrimaryGradientColor || "#389cff",
        buttonPrimaryRadius: parsed.settings.components?.buttonPrimaryRadius ?? 8,
        buttonPrimaryPaddingX: parsed.settings.components?.buttonPrimaryPaddingX ?? 24,
        buttonPrimaryPaddingY: parsed.settings.components?.buttonPrimaryPaddingY ?? 10,
        buttonSecondaryBg: parsed.settings.components?.buttonSecondaryBg || "transparent",
        buttonSecondaryText: parsed.settings.components?.buttonSecondaryText || "#ffffff",
        buttonSecondaryBorder: parsed.settings.components?.buttonSecondaryBorder || "rgba(255,255,255,0.3)",
        buttonSecondaryGradient: parsed.settings.components?.buttonSecondaryGradient || "none",
        buttonSecondaryGradientColor: parsed.settings.components?.buttonSecondaryGradientColor || "#8b5cf6",
        buttonSecondaryRadius: parsed.settings.components?.buttonSecondaryRadius ?? 8,
        buttonSecondaryPaddingX: parsed.settings.components?.buttonSecondaryPaddingX ?? 24,
        buttonSecondaryPaddingY: parsed.settings.components?.buttonSecondaryPaddingY ?? 10,
        cardBg: parsed.settings.components?.cardBg || "rgba(255,255,255,0.1)",
        cardBorder: parsed.settings.components?.cardBorder || "rgba(255,255,255,0.2)",
        cardGradient: parsed.settings.components?.cardGradient || "none",
        cardGradientColor: parsed.settings.components?.cardGradientColor || "#389cff",
        inputBg: parsed.settings.components?.inputBg || "#1a1a1a",
        inputBorder: parsed.settings.components?.inputBorder || "rgba(255,255,255,0.1)",
        inputText: parsed.settings.components?.inputText || "#ffffff",
        focusRingColor: parsed.settings.components?.focusRingColor || "#389cff",
        // Advanced gradient controls
        gradientType: parsed.settings.style?.gradientType || "linear",
        gradientAngle: parsed.settings.style?.gradientAngle ?? 135,
        blendMode: parsed.settings.style?.blendMode || "normal",
        noiseAmount: parsed.settings.style?.noiseAmount ?? 0,
        grainSize: parsed.settings.style?.grainSize || "medium",
        textureOpacity: parsed.settings.style?.textureOpacity ?? 0.5,
        radialFocusX: parsed.settings.style?.radialFocusX ?? 50,
        radialFocusY: parsed.settings.style?.radialFocusY ?? 50,
        exposure: parsed.settings.style?.exposure ?? 1,
        gamma: parsed.settings.style?.gamma ?? 1,
      };
    }
    return null;
  } catch {
    return null;
  }
};

export const HeroExportPanel: React.FC<HeroExportPanelProps> = ({
  isOpen,
  onClose,
  settings,
  onImportSettings,
}) => {
  const [activeTab, setActiveTab] = useState<"background" | "components">("background");
  const [copiedBg, setCopiedBg] = useState(false);
  const [copiedComp, setCopiedComp] = useState(false);
  const [copiedJSON, setCopiedJSON] = useState(false);
  const [importJSON, setImportJSON] = useState("");
  const [showImport, setShowImport] = useState(false);

  const handleCopyBackground = useCallback(async () => {
    const code = generateBackgroundComponent(settings);
    await navigator.clipboard.writeText(code);
    setCopiedBg(true);
    toast.success("Background component copied!");
    setTimeout(() => setCopiedBg(false), 2000);
  }, [settings]);

  const handleCopyComponents = useCallback(async () => {
    const code = generateComponentsCode(settings);
    await navigator.clipboard.writeText(code);
    setCopiedComp(true);
    toast.success("Components copied!");
    setTimeout(() => setCopiedComp(false), 2000);
  }, [settings]);

  const handleCopyJSON = useCallback(async () => {
    const json = generateSettingsJSON(settings);
    await navigator.clipboard.writeText(json);
    setCopiedJSON(true);
    toast.success("Settings JSON copied!");
    setTimeout(() => setCopiedJSON(false), 2000);
  }, [settings]);

  const handleImport = useCallback(() => {
    const parsed = parseSettingsJSON(importJSON);
    if (parsed) {
      onImportSettings(parsed);
      setImportJSON("");
      setShowImport(false);
      toast.success("Settings imported successfully!");
    } else {
      toast.error("Invalid settings JSON");
    }
  }, [importJSON, onImportSettings]);

  const backgroundCode = generateBackgroundComponent(settings);
  const componentsCode = generateComponentsCode(settings);

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[60] bg-black/60 backdrop-blur-sm flex items-center justify-center p-4"
          onClick={onClose}
        >
          <motion.div
            initial={{ scale: 0.95, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.95, opacity: 0, y: 20 }}
            className="w-full max-w-4xl max-h-[85vh] bg-neutral-950 border border-white/10 rounded-2xl overflow-hidden flex flex-col"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-white/5 flex-shrink-0">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-orange-500/20 text-orange-400">
                  <Code size={18} />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-white">Export Code</h2>
                  <p className="text-xs text-white/50">Export as React components</p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="p-2 rounded-lg hover:bg-white/5 text-white/50 hover:text-white transition-colors"
              >
                <X size={20} />
              </button>
            </div>

            {/* Tabs */}
            <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as "background" | "components")} className="flex-1 flex flex-col overflow-hidden">
              <TabsList className="mx-6 mt-4 bg-white/5 border border-white/10">
                <TabsTrigger value="background" className="data-[state=active]:bg-orange-500/20 data-[state=active]:text-orange-400">
                  Background
                </TabsTrigger>
                <TabsTrigger value="components" className="data-[state=active]:bg-cyan-500/20 data-[state=active]:text-cyan-400">
                  Components
                </TabsTrigger>
              </TabsList>

              {/* Background Tab */}
              <TabsContent value="background" className="flex-1 overflow-y-auto p-6 space-y-6 mt-0">
                {/* Description */}
                <div className="p-4 rounded-xl bg-orange-500/10 border border-orange-500/20">
                  <h3 className="text-sm font-semibold text-orange-400 mb-1">🎨 Hero Background Component</h3>
                  <p className="text-xs text-white/60 leading-relaxed">
                    Full-screen gradient tausta hero-sektioille. Sisältää valitsemasi värit, gradient-tyylin ({settings.gradientStyle}),
                    {settings.grainEnabled ? " grain-efektin," : ""}
                    {settings.environmentEnabled ? " environment-valon" : ""} ja brightness-säädöt.
                  </p>
                </div>

                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Code size={14} className="text-white/50" />
                      <span className="text-sm font-medium text-white">HeroBackground.tsx</span>
                    </div>
                    <button
                      onClick={handleCopyBackground}
                      className={cn(
                        "flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium border transition-all",
                        copiedBg
                          ? "bg-green-500/20 border-green-500/30 text-green-400"
                          : "bg-orange-500/20 border-orange-500/30 text-orange-400 hover:bg-orange-500/30"
                      )}
                    >
                      {copiedBg ? <Check size={14} /> : <Copy size={14} />}
                      {copiedBg ? "Copied!" : "Copy"}
                    </button>
                  </div>
                  <div className="bg-black/50 rounded-lg p-4 border border-white/5 max-h-80 overflow-y-auto">
                    <pre className="text-xs text-white/80 whitespace-pre-wrap font-mono leading-relaxed">
                      {backgroundCode}
                    </pre>
                  </div>
                  <p className="text-xs text-white/40">
                    💡 Käyttö: Wrap hero-sisältösi tällä komponentilla. Esim: &lt;HeroBackground&gt;&lt;YourContent /&gt;&lt;/HeroBackground&gt;
                  </p>
                </div>
              </TabsContent>

              {/* Components Tab */}
              <TabsContent value="components" className="flex-1 overflow-y-auto p-6 space-y-6 mt-0">
                {/* Description */}
                <div className="p-4 rounded-xl bg-cyan-500/10 border border-cyan-500/20">
                  <h3 className="text-sm font-semibold text-cyan-400 mb-1">🧩 UI Component Library</h3>
                  <p className="text-xs text-white/60 leading-relaxed">
                    Valmiit React-komponentit jotka vastaavat Components-välilehdellä muokkaamiasi tyylejä.
                    Sisältää napit, kortit ja input-kentät samoilla väreillä ja gradienteilla.
                  </p>
                </div>

                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Code size={14} className="text-white/50" />
                      <span className="text-sm font-medium text-white">UIComponents.tsx</span>
                    </div>
                    <button
                      onClick={handleCopyComponents}
                      className={cn(
                        "flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium border transition-all",
                        copiedComp
                          ? "bg-green-500/20 border-green-500/30 text-green-400"
                          : "bg-cyan-500/20 border-cyan-500/30 text-cyan-400 hover:bg-cyan-500/30"
                      )}
                    >
                      {copiedComp ? <Check size={14} /> : <Copy size={14} />}
                      {copiedComp ? "Copied!" : "Copy"}
                    </button>
                  </div>
                  <div className="bg-black/50 rounded-lg p-4 border border-white/5 max-h-80 overflow-y-auto">
                    <pre className="text-xs text-white/80 whitespace-pre-wrap font-mono leading-relaxed">
                      {componentsCode}
                    </pre>
                  </div>

                  {/* Component list */}
                  <div className="grid grid-cols-2 gap-2 mt-3">
                    <div className="p-2 rounded-lg bg-white/5 border border-white/10">
                      <span className="text-xs font-medium text-white/80">PrimaryButton</span>
                      <p className="text-[10px] text-white/40 mt-0.5">Pääpainike CTA-toiminnoille</p>
                    </div>
                    <div className="p-2 rounded-lg bg-white/5 border border-white/10">
                      <span className="text-xs font-medium text-white/80">SecondaryButton</span>
                      <p className="text-[10px] text-white/40 mt-0.5">Toissijainen toiminto</p>
                    </div>
                    <div className="p-2 rounded-lg bg-white/5 border border-white/10">
                      <span className="text-xs font-medium text-white/80">Card</span>
                      <p className="text-[10px] text-white/40 mt-0.5">Sisältökortti-komponentti</p>
                    </div>
                    <div className="p-2 rounded-lg bg-white/5 border border-white/10">
                      <span className="text-xs font-medium text-white/80">Input</span>
                      <p className="text-[10px] text-white/40 mt-0.5">Tekstikenttä lomakkeisiin</p>
                    </div>
                  </div>
                </div>
              </TabsContent>
            </Tabs>

            {/* Settings JSON Section */}
            <div className="px-6 pb-4 space-y-3 border-t border-white/5 pt-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FileJson size={14} className="text-white/50" />
                  <span className="text-sm text-white/70">Settings (JSON)</span>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => setShowImport(!showImport)}
                    className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium bg-white/5 border border-white/10 text-white/70 hover:bg-white/10 hover:text-white transition-all"
                  >
                    <Upload size={14} />
                    Import
                  </button>
                  <button
                    onClick={handleCopyJSON}
                    className={cn(
                      "flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium border transition-all",
                      copiedJSON
                        ? "bg-green-500/20 border-green-500/30 text-green-400"
                        : "bg-white/5 border-white/10 text-white/70 hover:bg-white/10"
                    )}
                  >
                    {copiedJSON ? <Check size={14} /> : <Download size={14} />}
                    {copiedJSON ? "Copied!" : "Copy JSON"}
                  </button>
                </div>
              </div>

              {showImport && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: "auto" }}
                  exit={{ opacity: 0, height: 0 }}
                  className="space-y-2"
                >
                  <textarea
                    value={importJSON}
                    onChange={(e) => setImportJSON(e.target.value)}
                    placeholder="Paste settings JSON here..."
                    className="w-full h-24 bg-black/50 rounded-lg p-3 border border-white/10 text-xs text-white/80 font-mono resize-none focus:outline-none focus-visible:outline-none focus:border-white/20 focus:ring-0 focus-visible:ring-0"
                  />
                  <button
                    onClick={handleImport}
                    disabled={!importJSON.trim()}
                    className="px-4 py-2 rounded-lg text-sm font-medium bg-cyan-500/20 border border-cyan-500/30 text-cyan-400 hover:bg-cyan-500/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Apply Settings
                  </button>
                </motion.div>
              )}
            </div>

            {/* Footer */}
            <div className="px-6 py-4 border-t border-white/5 flex items-center justify-between flex-shrink-0">
              <p className="text-xs text-white/40">
                Generated code matches the current preview 1:1
              </p>
              <button
                onClick={onClose}
                className="px-4 py-2 rounded-lg text-sm font-medium text-white/60 hover:text-white hover:bg-white/5 transition-all"
              >
                Close
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default HeroExportPanel;
