import React from "react";

/**
 * HeroBackground Component
 * Generated by Beymflow Hero Background Generator
 * 
 * Style: soft-sweep
 * Colors: #080808, #121214, #374151, #6b7280
 */

interface HeroBackgroundProps {
    children?: React.ReactNode;
    className?: string;
}

export const HeroBackground: React.FC<HeroBackgroundProps> = ({ children, className }) => {
    return (
        <div
            className={`relative w-full h-screen overflow-hidden ${className || ""}`}
            style={{
                background: "linear-gradient(135deg, #080808 0%, #08080890 10%, #121214 25%, #12121480 40%, #37415145 55%, #37415125 70%, #6b728030 85%, #080808 100%), radial-gradient(ellipse 100% 50% at 50% 25%, #37415120 0%, transparent 70%)",
                filter: "brightness(0.96)",
            }}
        >
            {/* Grain overlay */}
            <div
                className="absolute inset-0 pointer-events-none"
                style={{
                    backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E")`,
                    opacity: 0.024,
                    mixBlendMode: "overlay" as const,
                }}
            />

            {/* Content */}
            {children && (
                <div className="relative z-10 h-full">
                    {children}
                </div>
            )}
        </div>
    );
};

export default HeroBackground;
