import React from "react";

/**
 * StartBuildingBackground Component
 * Generated by Beymflow Hero Background Generator
 * 
 * Style: nebula-cloud
 * Colors: #000000, #00ecff, #000000, #4f00ff
 */

interface StartBuildingBackgroundProps {
    children?: React.ReactNode;
    className?: string;
}

export const StartBuildingBackground: React.FC<StartBuildingBackgroundProps> = ({ children, className }) => {
    return (
        <div
            className={`relative w-full overflow-hidden ${className || ""}`}
            style={{
                background: `
        radial-gradient(circle at 15% 50%, #00000040 0%, transparent 50%),
        radial-gradient(circle at 85% 30%, #4f00ff40 0%, transparent 50%),
        radial-gradient(circle at 50% 80%, #00ecff50 0%, transparent 60%),
        radial-gradient(at 50% 0%, #00000030 0%, transparent 50%),
        radial-gradient(at 0% 0%, #00ecff40 0%, transparent 50%),
        linear-gradient(180deg, transparent 0%, #000000 100%),
        #000000
      `,
                filter: "brightness(1)",
            }}
        >

            {/* Content */}
            {children && (
                <div className="relative z-10 h-full">
                    {children}
                </div>
            )}
        </div>
    );
};

export default StartBuildingBackground;
