import React from "react";

/**
 * VibeToolsBackground Component
 * Generated by Beymflow Hero Background Generator
 * 
 * Style: mesh
 * Colors: #000000, #000000, #000aff, #003cff
 */

interface VibeToolsBackgroundProps {
    children?: React.ReactNode;
    className?: string;
}

export const VibeToolsBackground: React.FC<VibeToolsBackgroundProps> = ({ children, className }) => {
    return (
        <div
            className={`relative w-full h-screen overflow-hidden ${className || ""}`}
            style={{
                background: "radial-gradient(at 40% 20%, #000aff60 0px, #000aff30 15%, transparent 55%), radial-gradient(at 80% 5%, #003cff55 0px, #003cff25 15%, transparent 55%), radial-gradient(at 5% 55%, #00000070 0px, #00000035 15%, transparent 55%), radial-gradient(at 85% 55%, #000aff45 0px, #000aff20 15%, transparent 55%), radial-gradient(at 10% 95%, #003cff60 0px, #003cff30 15%, transparent 55%), radial-gradient(at 85% 95%, #00000050 0px, #00000025 15%, transparent 55%), #000000, radial-gradient(ellipse 100% 50% at 50% 25%, #000aff20 0%, transparent 70%)",
                filter: "brightness(0.85) contrast(1.1) saturate(1.1)",
            }}
        >
            {/* Grain overlay */}
            <div
                className="absolute inset-0 pointer-events-none"
                style={{
                    backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E")`,
                    opacity: 0.075,
                    mixBlendMode: "overlay" as const,
                }}
            />
            {/* Vignette overlay */}
            <div
                className="absolute inset-0 pointer-events-none"
                style={{
                    background: "radial-gradient(ellipse 75% 65% at 50% 50%, transparent 35%, rgba(0,0,0,0.15) 65%, rgba(0,0,0,0.5) 100%)",
                    opacity: 0.35,
                    mixBlendMode: "multiply",
                }}
            />

            {/* Content */}
            {children && (
                <div className="relative z-10 h-full">
                    {children}
                </div>
            )}
        </div>
    );
};

export default VibeToolsBackground;
